runtime: nodejs22
service: default
handlers:
- url: /(.*\.(js|mjs))
  secure: always
  static_files: dist/\1
  upload: dist/(.*\.js)
  mime_type: text/javascript
- url: /(.*\.(ico|json|eot|ttf|woff|woff2|css|wasm))$
  secure: always
  static_files: dist/\1
  upload: dist/.*\.(ico|json|eot|ttf|woff|woff2|css|wasm)$
- url: /.*
  secure: always
  static_files: dist/index.html
  upload: dist/index.html