runtime: nodejs14
service: default
handlers:
- url: /(.*\.(ico|js|json|eot|ttf|woff|woff2|css))$
  secure: always
  static_files: dist/\1
  upload: dist/.*\.(ico|js|json|eot|ttf|woff|woff2|css)$
- url: /.*
  secure: always
  static_files: dist/index.html
  upload: dist/index.html